### ISSUE TITLE
fix : Problem running on MacOS with Docker and file path 

### ISSUE THREAD

**Issue by yumikim381** [Zipstack/unstract#239]
## Describe the bug

Could someone help me  resolve the following issue? 
I m trying to run the application on MacOS and encountering the following issue. 
First i got "Error response from daemon: Mounts denied: 
The path /Users/yk/Downloads/unstract-0.46.0/backend/init.sql is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing." 
Than when i added the file path "/Users/yk/Downloads/unstract-0.46.0" to Docker's file sharing path, this error occured. 
"Error response from daemon: error while creating mount source path '/Users/yk/Downloads/unstract-0.46.0/docker/workflow_data': mkdir /Users: file exists". 

## To reproduce
Downloaded latest Release [v0.46.0](https://github.com/Zipstack/unstract/releases/tag/v0.46.0), and tried to run ./run-platform.sh. 

## Expected behavior
Running the application on website

## Environment details
 -  [v0.46.0]
 - I have M1 macbook.

**Comment by nehabagdia** [comment]
Hi Yumi, 
We are looking into this and will get back to you shortly. 
Thanks, 
Neha

**Comment by ritwik-g** [comment]
Hi @yumikim381 ,
This is most likely a mac file permission issue. For folders like Downloads, Documents etc, in mac we might need to provide specific access permission. 

Usually a pop up should appear asking if docker should be given access to Downloads folder. If this was not provided you could face the issue that you are facing. 

To resolve this please try turning this access on in Mac settings. Setting -> Privacy & Security -> Files and Folders -> Docker -> Enable Downloads Folder

<img width="468" alt="image" src="https://github.com/Zipstack/unstract/assets/100672805/799b316b-b0a0-469b-852a-8511a8d25984">
<img width="461" alt="image" src="https://github.com/Zipstack/unstract/assets/100672805/8028d87c-9ddf-4a44-9524-68c48c02b5eb">
<img width="468" alt="image" src="https://github.com/Zipstack/unstract/assets/100672805/1dc18aa1-0b7e-415d-a18b-802e5957d1c0">

**Or even easier might be moving downloaded folder under your user's home folder and trying.**

PS: You might need to remove shared path setting you mentioned if any other issues are arising. 

Please try and let us know if you were able to solve the problem.

**Comment by yumikim381** [comment]
Seems to work!! Thank you so much
