### ISSUE TITLE
credentials issue

### ISSUE THREAD

**Issue by IsraelAbebe** [Zipstack/unstract#240]
I was playing around with the opensource local deployment and was having a problem with the credentials 
what am i doing wrong?

![image](https://github.com/Zipstack/unstract/assets/15804692/e3cb5988-90c1-4e09-a67c-8f43a63e2483)

**Comment by VikashPratheepan** [comment]
Hi @IsraelAbebe

1)Clear the docker volumes by running the below command from project root directory.
`docker compose -f docker/docker-compose.yaml down -v`
2) Update the project using  `./run-platform.sh --upgrade`.
3)Copy the **# System admin credentials** from 'unstract/backend/sample.env' and replace it in  'unstract/backend/.env 'file

(Or)

1)Clear the old docker volumes by running the below  command from project root directory.
`docker compose -f docker/docker-compose.yaml down -v`
2)Clone the new project and run the script ` ./run-platform.sh`

**Comment by ritwik-g** [comment]
@IsraelAbebe to add more context probably you haven't done anything wrong. Around last Friday we had a change which went in that caused this issues. So if you cloned repo around that time that would be the reason.

Above steps shared are to work around that issue if you indeed had cloned around that time.

**Comment by ritwik-g** [comment]
@IsraelAbebe it would be great to know if the above steps helped to resolve your issue.

**Comment by ritwik-g** [comment]
Closing stale issue
