### ISSUE TITLE
privacy when self-hosting

### ISSUE THREAD

**Issue by legaltextai** [Zipstack/unstract#427]
I 've been playing with your hosted version. It's impressive. I 've tried all known parsers, including llamaparse and unstructured. But your parsing of bank/credict card statements is second to none. Great job! 
If I self - host, does it mean LLMWhisperer is run locally too? 
My biggest concern is the privacy, I 'd like to ensure everything stays local. I plan to use ollama models for both embeddings and LLM. 
Which of the open source models worked best in your experience? 
Thank you

**Comment by shuveb** [comment]
@legaltextai yes. LLMWhisperer can be privately hosted. Your data won't leave your network that way.

**Comment by shuveb** [comment]
@legaltextai missed your query about open source models. Llama3 is probably the best, at least for now.

**Comment by legaltextai** [comment]
thank you very much @shuveb
