### ISSUE TITLE
fix: not installing with ./run-platform

### ISSUE THREAD

**Issue by legaltextai** [Zipstack/unstract#438]
Ubuntu, Linux 64, Server 
Initial Issue: The run-platform.sh script was failing silently.
Main Problems Identified:
a. Missing environment files (.env) for various services.
b. Missing essentials.env file in the docker directory.
c. The script was using docker compose (with a space) which wasn't working on my system.
Steps to Resolution:
a. Created empty .env files for each service
touch backend/.env frontend/.env platform-service/.env prompt-service/.env worker/.env x2text-service/.env 
cp docker/sample.essentials.env docker/essentials.env
VERSION=latest /usr/local/bin/docker-compose -f docker/docker-compose.yaml up -d

**Comment by ritwik-g** [comment]
Script we have is written in a way to use [`compose` ](https://docs.docker.com/compose/install/linux/) plugin.

I think you might need a newer version of `docker` for this. Can you try installing this plugin and running the script?

**Comment by ritwik-g** [comment]
> Script we have is written in a way to use [`compose` ](https://docs.docker.com/compose/install/linux/) plugin.
> 
> I think you might need a newer version of `docker` for this. Can you try installing this plugin and running the script? 

My understanding was wrong. Looks like the script supports both compose plugin as well as docker-compose cli. 

So the script should have worked for you. Could you share some screenshots from when the script is failing?

**Comment by ritwik-g** [comment]
@legaltextai Also to get further idea can you run the below commands and share its results.

```
docker --version
docker compose version
docker-compose version
```

**Comment by legaltextai** [comment]
i can start with ./run-platform.sh now , and can access with curl on my server. i think the issue was with the compose version. 
thank you for your help
