### ISSUE TITLE
fix: [ISSUE] 500 Internal server error when login

### ISSUE THREAD

**Issue by haluwong** [Zipstack/unstract#469]
version: v0.73.0
OS: ubuntu 22.04
Fresh installation of unstract by downloading v0.73.0.tar.gz
decompress and execute ./run-platform.sh

access through http://frontend.unstract.localhost, fill the login and then redirect back to login page again.

https://github.com/Zipstack/unstract/assets/2929231/5f8a1fde-3ea1-42be-bb1c-d48c2100b1bd

![Uploading screen_20240710_11.png…]()

**Comment by chandrasekharan-zipstack** [comment]
Hey @haluwong ,

1. Can you share a traceback of the backend logs? It's not very evident from the video.
1. Do you recall updating [this ENCRYPTION_KEY](https://github.com/Zipstack/unstract/blob/e45061795e2bf203df031ca904f5d9185515ac1a/backend/sample.env#L108) environment variable in your `backend.env` by any chance?
1. By a fresh installation of unstract, do you also mean that there's no pre-existing data?

**Comment by haluwong** [comment]
> Hey @haluwong ,
> 
>     1. Can you share a traceback of the backend logs? It's not very evident from the video.
> 
>     2. Do you recall updating [this ENCRYPTION_KEY](https://github.com/Zipstack/unstract/blob/e45061795e2bf203df031ca904f5d9185515ac1a/backend/sample.env#L108) environment variable in your `backend.env` by any chance?
> 
>     3. By a fresh installation of unstract, do you also mean that there's no pre-existing data?

Thanks, I forgot to clear the volume and also didn't update the ENCRYPTION_KEY.
Now can access the system.
