### ISSUE TITLE
Document how to add new adapters

### ISSUE THREAD

**Issue by abc-w** [Zipstack/unstract#716]
May I ask for your advice，how can i modify code  to use my personal fintune LLM and ocr tool？

**Comment by ritwik-g** [comment]
If you are running the LLM via ollama you can connect to the system. For the personal OCR if it is not in the list of supported adapters currently you can't use with the platform. 
We don't have documentation on how to add a new connector as of now cc: @arun-venkataswamy @hari-kuriakose @gaya3-zipstack

**Comment by hari-kuriakose** [comment]
@abc-w Please find the updated steps to add a new adapter here:
https://docs.unstract.com/unstract/contributing/unstract/sdk/contribute-adapter/

That being said, as mentioned we already support Ollama if that's how you are deploying your LLM, or you might have to write a custom LLM adapter as outlined in the doc above.

For your custom OCR tool, you might have to write a custom X2Text adapter as per the same doc.
