### ISSUE TITLE
[ISSUE] relation "user" does not exist

### ISSUE THREAD

**Issue by ferdyhong** [Zipstack/unstract#842]
✅ ./run-platform.sh
✅ Now visit http://frontend.unstract.localhost/ in your browser
✅ Use user name and password unstract to login

## Describe the bug
The following error occurs when attempting to log in at http://frontend.unstract.localhost.

- relation "user" does not exist

![unstract_login_error](https://github.com/user-attachments/assets/6fb86a69-e1b8-4074-b5e3-fe8b60f76a17)

## To reproduce

I simply followed this sequence.

✅ ./run-platform.sh
✅ Now visit http://frontend.unstract.localhost/ in your browser
✅ Use user name and password 'unstract' to login

## Expected behavior
I expected the login to succeed and transition to the main screen of Unstract.

## Environment details
 - Version: 0.96.0

Request Method: POST
Request URL: http://frontend.unstract.localhost/api/v1/login

Django Version: 4.2.1
Python Version: 3.9.20
Installed Applications:
['corsheaders',
 'account_v2',
 'account_usage',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.admindocs',
 'rest_framework',
 'social_django',
 'drf_yasg',
 'docs',
 'plugins',
 'feature_flag',
 'django_celery_beat',
 'commands',
 'migrating.v2',
 'connector_auth_v2',
 'tenant_account_v2',
 'connector_v2',
 'adapter_processor_v2',
 'file_management',
 'workflow_manager.endpoint_v2',
 'workflow_manager.workflow_v2',
 'tool_instance_v2',
 'pipeline_v2',
 'platform_settings_v2',
 'api_v2',
 'usage_v2',
 'notification_v2',
 'prompt_studio.prompt_profile_manager_v2',
 'prompt_studio.prompt_studio_v2',
 'prompt_studio.prompt_studio_core_v2',
 'prompt_studio.prompt_studio_registry_v2',
 'prompt_studio.prompt_studio_output_manager_v2',
 'prompt_studio.prompt_studio_document_manager_v2',
 'prompt_studio.prompt_studio_index_manager_v2']
Installed Middleware:
['log_request_id.middleware.RequestIDMiddleware',
 'corsheaders.middleware.CorsMiddleware',
 'middleware.organization_middleware.OrganizationMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'account_v2.custom_auth_middleware.CustomAuthMiddleware',
 'middleware.exception.ExceptionLoggingMiddleware',
 'social_django.middleware.SocialAuthExceptionMiddleware',
 'middleware.remove_allow_header.RemoveAllowHeaderMiddleware',
 'middleware.cache_control.CacheControlMiddleware']

## Additional context

it seems that Django is not running properly on the backend, which is likely causing tables like the user table not to be created.
For reference, I am using Ubuntu through WSL on Windows, and I have installed it on WSL.

## Screenshots
The login screen fails to load the logo image.
![unstract_no_logo](https://github.com/user-attachments/assets/301ab176-0a50-4d29-858f-950d3028012c)

This is the result of a table query in PostgreSQL. As you can see, there is no user table.
![unstract_postgres_db](https://github.com/user-attachments/assets/a379e5a2-18e6-448d-bcda-56a340429a57)

**Comment by chandrasekharan-zipstack** [comment]
Hey @ferdyhong, 

May I know which version of Unstract you're trying out here? (`git describe --tags --abbrev=0` can help)

- If you've tried upgrading from a version `<v0.93.0`
    - If the old data is important to you, you might have to follow [these steps to migrate to V2](https://github.com/Zipstack/unstract/blob/125a9304cc30c88893a552071b1bb0611b035073/backend/migrating/v2/README.md#L12)
    - If not, you can clear the DB (remove the volume if its our postgres DB) and use Unstract with a fresh database. Please remove your `backend/.env` and `platform-service/.env`  and run `./run-platform.sh` to trigger the table and schema creation again

**Comment by chandrasekharan-zipstack** [comment]
Happy that you're able to proceed @ferdyhong, there's no explicit difference between git clone and the latest release version because  `./run-platform.sh` uses the `latest` image by default. 

Here's a possible root cause for it,
we determine if the user is setting up Unstract for the first time by checking the presence of `.env` files within the services and then we create the schema in the DB. If for some reason the `./run-platform.sh` script is interrupted in between, it could have created the necessary `.env` files but not the schema in the DB and we might face this error on subsequent runs

Will check with the team and try to improve the UX here. Feel free to drop any feedback around this

**Comment by chandrasekharan-zipstack** [comment]
@ferdyhong We've made some [changes to this schema creation flow](https://github.com/Zipstack/unstract/pull/864) and its part of [v0.99.0](https://github.com/Zipstack/unstract/releases/tag/v0.99.0). This will kick in for fresh clones / runs with a new DB - I hope this solves such issues you face. Feel free to reopen it if it persists
